// Auto-generated by scripts/generate-env.mjs. Do not edit directly.
export const environment = {
  production: false,
  supabaseUrl: 'http://localhost:54321',
  supabaseAnonKey: 'SUPABASE_ANON_DEV_KEY'
};
