// Auto-generated by scripts/generate-env.mjs. Do not edit directly.
export const environment = {
  production: true,
  supabaseUrl: 'https://your-supabase-project.supabase.co',
  supabaseAnonKey: 'SUPABASE_ANON_PUBLIC_KEY'
};
