import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const envDir = path.resolve(__dirname, '../apps/web/src/environments');

const configs = [
  {
    filename: 'environment.ts',
    production: true,
    supabaseUrl: process.env.SUPABASE_URL ?? 'https://your-supabase-project.supabase.co',
    supabaseAnonKey: process.env.SUPABASE_ANON_KEY ?? 'SUPABASE_ANON_PUBLIC_KEY'
  },
  {
    filename: 'environment.development.ts',
    production: false,
    supabaseUrl:
      process.env.SUPABASE_URL_DEV ?? process.env.SUPABASE_URL ?? 'http://localhost:54321',
    supabaseAnonKey:
      process.env.SUPABASE_ANON_KEY_DEV ?? process.env.SUPABASE_ANON_KEY ?? 'SUPABASE_ANON_DEV_KEY'
  }
];

const banner = '// Auto-generated by scripts/generate-env.mjs. Do not edit directly.\n';

configs.forEach((config) => {
  const content = `${banner}export const environment = {\n  production: ${config.production},\n  supabaseUrl: '${config.supabaseUrl}',\n  supabaseAnonKey: '${config.supabaseAnonKey}'\n};\n`;
  fs.writeFileSync(path.join(envDir, config.filename), content, 'utf-8');
  console.log(`Wrote ${config.filename} using ${config.production ? 'production' : 'development'} env vars.`);
});
